items:
  - name: "apple"
    price: "1.00"

  - name: "bread"
    price: "0.80"

  - name: "milk"
    price: "1.30"

  - name: "soup"
    price: "0.65"

discounts:
  - target: "apple"
    startDate: "15/07/2018"
    endDate: "22/07/2018"
    discountQuantityCondition: "1"
    discountItemCondition: "apple"
    discountPercentage: "10.00"

  - target: "apples"
    startDate: "15/07/2018"
    endDate: "22/07/2018"
    discountQuantityCondition: "1"
    discountItemCondition: "apples"
    discountPercentage: "10.00"

  - target: "bread"
    discountQuantityCondition: "2"
    discountItemCondition: "soup"
    discountPercentage: "50.00"